name: Hello World Docker CI
on:
  push:
    branches: [ main ]
    paths: [hello-world-docker-action]
  workflow_dispatch:
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Run container
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@sporturo'

      - name: Output time
        run: echo "The time is ${{  steps.hello-action.outputs.time }}"
